// Package gcp provides Google Cloud Platform deployment helpers.
package gcp

import (
	"context"
	"fmt"

	artifactregistrypb "cloud.google.com/go/artifactregistry/apiv1/artifactregistrypb"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// DefaultRepoName is the default Artifact Registry repository name.
const DefaultRepoName = "mint-mcp-servers"

// RegistryClient abstracts the Artifact Registry API for testability.
type RegistryClient interface {
	GetRepository(ctx context.Context, name string) (*artifactregistrypb.Repository, error)
	CreateRepository(ctx context.Context, req *artifactregistrypb.CreateRepositoryRequest) (*artifactregistrypb.Repository, error)
}

// EnsureRepository checks whether an Artifact Registry Docker repository
// exists and creates it if it does not. It returns the repository URI
// (e.g. "us-central1-docker.pkg.dev/my-project/mint-mcp-servers").
func EnsureRepository(ctx context.Context, client RegistryClient, projectID, region, repoName string) (string, error) {
	if repoName == "" {
		repoName = DefaultRepoName
	}

	name := fmt.Sprintf("projects/%s/locations/%s/repositories/%s", projectID, region, repoName)

	_, err := client.GetRepository(ctx, name)
	if err == nil {
		return repoURI(region, projectID, repoName), nil
	}

	st, ok := status.FromError(err)
	if !ok || st.Code() != codes.NotFound {
		return "", fmt.Errorf("get repository: %w", err)
	}

	parent := fmt.Sprintf("projects/%s/locations/%s", projectID, region)
	req := &artifactregistrypb.CreateRepositoryRequest{
		Parent:       parent,
		RepositoryId: repoName,
		Repository: &artifactregistrypb.Repository{
			Format:      artifactregistrypb.Repository_DOCKER,
			Description: "Docker repository for MCP servers generated by mint",
		},
	}

	_, err = client.CreateRepository(ctx, req)
	if err != nil {
		return "", fmt.Errorf("create repository: %w", err)
	}

	return repoURI(region, projectID, repoName), nil
}

func repoURI(region, projectID, repoName string) string {
	return fmt.Sprintf("%s-docker.pkg.dev/%s/%s", region, projectID, repoName)
}
